CREATE SEQUENCE HIBERNATE_SEQUENCE AS BIGINT INCREMENT BY 1 START WITH 1;

CREATE TABLE ACCOUNT
(
    ID      BIGINT,
    BALANCE  NUMERIC NOT NULL CHECK (BALANCE >= 0),
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID)
);
