CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE ACCOUNT
(
    ID      BIGINT,
    BALANCE NUMERIC NOT NULL DEFAULT 0,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID),
    CONSTRAINT ACCOUNT_BALANCE_CHECK CHECK (BALANCE >= 0)
);
