CREATE SEQUENCE HIBERNATE_SEQUENCE AS BIGINT INCREMENT BY 1 START WITH 1;

CREATE TABLE ACCOUNT
(
    ID      BIGINT,
    BALANCE NUMERIC NOT NULL DEFAULT 0,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ID),
    CONSTRAINT ACCOUNT_BALANCE_CHECK CHECK (BALANCE >= 0)
);
