CREATE TABLE OPERATION
(
    ID          BIGINT,
    ACCOUNT_ID  BIGINT NOT NULL,
    TYPE        VARCHAR(1) NOT NULL,
    AMOUNT      NUMERIC NOT NULL,
    DATE        TIMESTAMP NOT NULL,
    CONSTRAINT OPERATION_PKEY PRIMARY KEY (ID),
    CONSTRAINT OPERATION_ACCOUNT_ID_FKEY FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT OPERATION_AMOUNT_CHECK CHECK (AMOUNT > 0)
);

CREATE INDEX OPERATION_ACCOUNT_ID_IDX ON OPERATION(ACCOUNT_ID);
