CREATE TABLE TRANSFER
(
    ID          BIGINT,
    DEBIT_ID    BIGINT NOT NULL,
    CREDIT_ID   BIGINT NOT NULL,
    CONSTRAINT TRANSFER_PKEY PRIMARY KEY (ID),
    CONSTRAINT TRANSFER_DEBIT_ID_FKEY FOREIGN KEY (DEBIT_ID) REFERENCES OPERATION(ID),
    CONSTRAINT TRANSFER_CREDIT_ID_FKEY FOREIGN KEY (CREDIT_ID) REFERENCES OPERATION(ID)
);

CREATE INDEX TRANSFER_DEBIT_ID_IDX ON TRANSFER(DEBIT_ID);
CREATE INDEX TRANSFER_CREDIT_ID_IDX ON TRANSFER(CREDIT_ID);
