CREATE TABLE TRANSFER
(
    ID                      BIGINT,
    OUTGOING_TRANSFER_ID    BIGINT NOT NULL,
    INCOMING_TRANSFER_ID    BIGINT NOT NULL,
    CONSTRAINT TRANSFER_PKEY PRIMARY KEY (ID),
    CONSTRAINT TRANSFER_OUTGOING_TRANSFER_ID_FKEY FOREIGN KEY (OUTGOING_TRANSFER_ID) REFERENCES OPERATION(ID),
    CONSTRAINT TRANSFER_INCOMING_TRANSFER_ID_FKEY FOREIGN KEY (INCOMING_TRANSFER_ID) REFERENCES OPERATION(ID)
);

CREATE INDEX TRANSFER_OUTGOING_TRANSFER_ID_IDX ON TRANSFER(OUTGOING_TRANSFER_ID);
CREATE INDEX TRANSFER_INCOMING_TRANSFER_ID_IDX ON TRANSFER(INCOMING_TRANSFER_ID);
